version: 2
jobs:
  black_box_integration:
    machine:
        image: circleci/classic:201808-01
    working_directory: ~/cilantro
    parallelism: 1
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages
      - restore_cache:
          key: cilantro-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}-integration
      - run: pyenv local 3.6.5

      - run:
          name: Login to Docker
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PWD

      - run:
          name: Login to AWS
          command: |
            mkdir -p ~/.aws
            cat << EOF > ~/.aws/credentials
            [default]
            aws_access_key_id = $AMZN_ACCESS_KEY
            aws_secret_access_key = $AMZN_SECRET_KEY
            EOF

      - run:
          name: Install Devops Requirements
          command: |
            apt-get install terraform
            pip3 install pathspec

      - run:
          name: Stand up terraform nodes
          command: |
             cd ops/environments/circleci && ADDITIONAL_FLAGS="-auto-approve" make run 

      - run:
          name: Run Currency Test
          command: |
              cd ops/environments/circleci && make testcurr

#      - run:
#          name: Run SmartContract Test
#          command: |
#              cd ops/environments/circleci && make testsc

      - save_cache:
          key: cilantro-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}-integration
          paths:
            - "/usr/local/bin"
            - "/opt/circleci/"

version: 2
jobs:
  unit_tests:
    machine:
        image: circleci/classic:201808-01
    working_directory: ~/cilantro
    parallelism: 1
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages
      - restore_cache:
          key: cilantro-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}-integration
      - run: pyenv local 3.6.5

      - run:
          name: Login to Docker
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PWD

      - run:
          name: Download Base Images
          command: |
            docker pull lamden/cilantro_base:circleci
            docker pull lamden/cilantro_full:circleci
            docker pull lamden/cilantro_light:circleci

      - run:
          name: Build and Push Docker Image
          command: |
             ./ops/tools/docker_build_push.sh --push

      - run:
          name: Spinup Docker Image
          command: |
             echo "SHOULD RUN DOCKER IMAGES HEREEERRERERERERERERERE"
             sudo docker run --name cil -dit -v /var/db/cilantro/:/var/db/cilantro -v ~/cilantro/ops/base/redis.conf:/etc/redis.conf -v ~/cilantro/ops/base/circus_unittest.conf:/etc/circus.conf lamden/cilantro_full:$(bash ~/cilantro/ops/tools/generate_tag.sh)

      - run:
          name: Docker Exec and Run Test
          command: |
            docker exec -it cil /app/scripts/start_unit_tests.sh

      - save_cache:
          key: cilantro-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}-integration
          paths:
            - "/usr/local/bin"

workflows:
  version: 2
  build_and_test_cilantro:
    jobs:
      - unit_tests
#      - black_box_integrations