version: 2
jobs:
  black_box_integration:
    machine:
        image: circleci/classic:201808-01
    working_directory: ~/cilantro
    parallelism: 1
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages
      - restore_cache:
          key: cilantro-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}-integration
      - run: pyenv local 3.6.5

      - run:
          name: Install Cilantro Requirements
          command: |
             pip install -r requirements.txt --upgrade --no-cache-dir --exists-action w
             pip install -r dev-requirements.txt --upgrade --no-cache-dir --exists-action w
        
      - run:
          name: Stand up terraform nodes
          command: |
             cd ops/environments/circleci && ADDITIONAL_FLAGS="-auto-approve" make run 

      - run:
          name: Run test
          command: |
              cd ops/environments/circleci && make test
  integration_tests:
    machine:
        image: circleci/classic:201808-01
    working_directory: ~/cilantro
    parallelism: 5
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages
      - restore_cache:
          key: cilantro-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}-integration
      - run: pyenv local 3.6.5

      - run:
          name: Install Cilantro Requirements
          command: |
             pip install -r requirements.txt --upgrade --no-cache-dir --exists-action w
             pip install -r dev-requirements.txt --upgrade --no-cache-dir --exists-action w

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.03.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/local/bin

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - save_cache:
          key: cilantro-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}-integration
          paths:
            - "/usr/local/bin"
            - "/opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages"

      - run:
          name: Run Tests
          command: |
            export PYTHONPATH=$PYTHONPATH:~/cilantro
            export LOCAL_PATH=~
            python3 ./scripts/make_test_config.py
            python3.6 ~/cilantro/tests/run_tests.py --integration 1 --unit 0

  unit_tests:
    working_directory: ~/cilantro
    docker:
      - image: circleci/python:3.6.5
      - image: lamden/cilantro-mn
        environment:
          username: cilantro_user
          password: buttcoins
          database: cilantro_dev
    parallelism: 1
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: cilantro-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}-unit

      - run:
          name: Install Cilantro Requirements
          command: |
             sudo pip3 install -r requirements.txt --upgrade --no-cache-dir --exists-action w
             sudo pip3 install -r dev-requirements.txt --upgrade --no-cache-dir --exists-action w

      - run:
          name: Install Redis
          command: |
             sudo apt-get install redis-server

      - run:
          name: Install Mongo
          command: |
             sudo apt-get install mongodb
             sudo mkdir -p /data/db

      - save_cache:
          key: cilantro-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}-unit
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

      - run:
          name: Run Tests
          command: |
            redis-server &
            sudo mongod &
            python3.6 ~/cilantro/scripts/create_user.py
            export PYTHONPATH=$PYTHONPATH:~/cilantro
            export LOCAL_PATH=~
            python3.6 ~/cilantro/tests/run_tests.py --integration 0 --unit 1 --skip_modules tests.unit.nodes.masternode tests.unit.nodes.delegate

      - run:
          mkdir -p unit-test-results

      - store_test_results:
          path: unit-test-results

workflows:
  version: 2
  build_and_test_cilantro:
    jobs:
      - unit_tests
      - integration_tests
